### ISSUE TITLE
The "I should see/not see element" step definitions are not working with chrome driver

### ISSUE THREAD

**Issue by danielantelo** [Adezandee/cucumber-mink#211]
The reply from chrome driver for elementState isVisible is an array and not a boolean.

```
AssertionError: expected [ false, false, false ] to equal false
```

I'm using ChromeDriver 2.24.417412 (ac882d3ce7c0d99292439bf3405780058fcca0a6)

Is there a particular version of chrome driver we should be using?

**Comment by Adezandee** [comment]
Hi @danielanteloagra, I've never seen such compatibility errors. I use protactor's webdriver-manager package to launch the selenium server usually.
Anyway seems to me that this kind of error should be handled inside WebdriverIO right?

**Comment by danielanteloagra** [comment]
After playing around a bit more, this happens when the selector finds more than one item. E.g. say you have 3 .my-element in a page, if all are hidden you get back [false, false, false] which should pass the test if you want to verify an element of that class is not visible. Currently it fails trying to compare an array to a boolean.

So here https://github.com/Adezandee/cucumber-mink/blob/master/src/step_definitions/assert_dom.js#L67 it should check if isMethod is an array or boolean before comparing it to state and act accordingly, I will PR my fix.
